# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
      - cron: '0 6 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install BeautifulSoup4
        pip install gevent
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup Deploy Private Key
      env:
        DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: main
      run: |
        python 爬取极简壁纸2.0.py
    - name: uploads
      run: |
        git config --global user.name "techoc" # 改成Github账号用户名
        git config --global user.email "543938801@qq.com" # 改成GitHub账号的邮箱
        cd /home/runner/work/Minimalism-wallpaper-crawler/Minimalism-wallpaper-crawler/极简壁纸
        git add "*.jpg" "*.png" && echo "Git Added"
        git commit -m 'upload pa result' && echo "Git Committed"
        git push -u origin git@github.com:Techoc/Minimalism-wallpaper-crawler-images.git && echo "Git Pushed Origin" # runner改成存放图片的分支
